# Comparison Operators
## NumPy recap

In [19]:
# Code from Intro to Python for Data Science, Chapter 4
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [20]:
print(bmi > 23)

[False False False  True False]


In [6]:
bmi[bmi > 23]

array([24.7473475])

* Comparison operators: how Python values relate

## Numeric comparisons

In [7]:
2 < 3

True

In [8]:
2 == 3

False

In [9]:
2 <= 3

True

In [10]:
3 <= 3

True

In [11]:
x = 2
y = 3
x < y

True

Other comparisons

In [12]:
"carl" < "chris"

True

In [13]:
3 < "chris"

TypeError: '<' not supported between instances of 'int' and 'str'

In [14]:
3 < 4.1

True

## Other comparisons

In [17]:
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [18]:
print(bmi > 23)

[False False False  True False]


In [21]:
print(bmi[bmi > 23])

[24.7473475]


## Comparators
| Comparator | Meaning               |
|------------|-----------------------|
| `<`        | Strictly less than    |
| `<=`       | Less than or equal    |
| `>`        | Strictly greater than |
| `>=`       | Greater than or equal |
| `==`       | Equal                 |
| `!=`       | Not equal             |
